inherit_gem:
  rubocop-github:
    - config/default.yml
    - config/rails.yml

# File Exclusions
AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/schema.rb
    - db/migrate/*.rb

# Rubocop for Rspec (Tests)
require: rubocop-rspec

# NGS Specific Overrides
GitHub/RailsControllerRenderPathsExist:
  # Doesn't seem to work; can't find templates that exist.
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

