inherit_gem:
  rubocop-github:
    - config/default.yml
    - config/rails.yml

# File Exclusions
AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/schema.rb
    - db/migrate/*.rb
    - spec/rails_helper.rb
    - spec/spec_helper.rb

# NGS Specific Overrides
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
