inherit_gem:
  rubocop-github:
    - config/default.yml
    - config/rails.yml

# File Exclusions
AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/schema.rb
    - db/migrate/*.rb

# Rubocop for Rspec (Tests)
require: rubocop-rspec

# NGS Specific Overrides
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
